// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG4aUJ39lk7cMubY4vJqAKcIKoWBDvA9M',
    appId: '1:947472672630:web:859c94ab3a9ebd40a1fc57',
    messagingSenderId: '947472672630',
    projectId: 'mobile-e1ac5',
    authDomain: 'mobile-e1ac5.firebaseapp.com',
    storageBucket: 'mobile-e1ac5.firebasestorage.app',
    measurementId: 'G-NJ7GH4S57Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ_OvpXu98nrUKPheZOHZ98hLX8g0kB_Y',
    appId: '1:947472672630:android:5d2b9b2be1e0d661a1fc57',
    messagingSenderId: '947472672630',
    projectId: 'mobile-e1ac5',
    storageBucket: 'mobile-e1ac5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUkNIGMjXTmvowsutpj2wKJ0qeBnofaM',
    appId: '1:947472672630:ios:6515a1236cedcd4aa1fc57',
    messagingSenderId: '947472672630',
    projectId: 'mobile-e1ac5',
    storageBucket: 'mobile-e1ac5.firebasestorage.app',
    iosClientId: '947472672630-rk3h02qg5nj1af40d0radefb1557hbja.apps.googleusercontent.com',
    iosBundleId: 'com.example.btl',
  );
}
