import 'package:flutter/material.dart';

class AppLanguge {
  AppLanguge(this.locale);

  final Locale locale;

  static AppLanguge? of(BuildContext context) {
    return Localizations.of<AppLanguge>(context, AppLanguge);
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'settingsTitle': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'lightTheme': 'Light',
      'darkTheme': 'Dark',
      'systemTheme': 'System',
      'english': 'English',
      'vietnamese': 'Vietnamese',
      'homeTitle': 'Home',
      'adminPanelTitle': 'Admin Panel',
      'adminPanelSubtitle': 'Manage places, study documents, and user reports',
      'managePlaces': 'Manage places',
      'manageDocuments': 'Manage documents',
      'reviewReports': 'Review reports',
      'featuredContent': 'Featured content',
      'approvalQueue': 'Approval queue',
      'moderationSectionTitle': 'Moderation tools',
      'placesAdminDescription': 'Approve, hide, and organize shared study locations from users.',
      'documentsAdminDescription': 'Moderate learning materials, tags, and quality before publishing.',
      'quickActions': 'Quick actions',
      'quickActionAddPlace': 'Add place',
      'quickActionReviewPlace': 'Review places',
      'quickActionAddDocument': 'Add document',
      'quickActionReviewDocument': 'Review documents',
      'reportReasonLabel': 'Reason',
      'reportByLabel': 'Reported by',
      'dismissReportButton': 'Dismiss',
      'takeActionButton': 'Take action',
      'approveButton': 'Approve',
      'rejectButton': 'Reject',
      'setFeaturedButton': 'Set featured',
      'active': 'Active',
      'pending': 'Pending',
      'totalItems': 'Total items',
      'viewAll': 'View all',
      'homeWelcomeSubtitle': 'Discover places and study resources shared by the community',
      'searchHint': 'Search places, documents, topics...',
      'newPlacesMetric': 'New places',
      'newDocumentsMetric': 'New docs',
      'savedMetric': 'Saved',
      'newAndFeaturedSection': 'New & Featured places and documents',
      'filterButton': 'Filter',
      'featuredPlaceTitle': 'Group-study cafe near campus',
      'featuredPlaceSubtitle': 'Quiet space, stable wifi, open until 11 PM',
      'featuredDocTitle': 'IELTS Writing Task 2 Guide',
      'featuredDocSubtitle': 'Updated checklist and band 7+ sample essays',
      'placeTag': 'Place',
      'documentTag': 'Document',
      'mySharingSection': 'My sharing space',
      'myPostsButton': 'My posts',
      'newPostButton': 'New post',
      'shareDocumentButton': 'Share study document',
      'openMapButton': 'Open map',
      'mapExploreTitle': 'Explore map',
      'searchPageTitle': 'Search',
      'suggestedKeywords': 'Suggested keywords',
      'filterPageTitle': 'Filter content',
      'featuredOnly': 'Only featured',
      'distanceRangeLabel': 'Distance range',
      'applyFilterButton': 'Apply filter',
      'discoverPageTitle': 'Discover places and documents',
      'postTitleLabel': 'Post title',
      'postContentLabel': 'Post content',
      'publishPostButton': 'Publish post',
      'documentTitleLabel': 'Document title',
      'documentSubjectLabel': 'Subject / category',
      'documentDescriptionLabel': 'Description',
      'pickDocumentButton': 'Pick file',
      'submitDocumentButton': 'Submit document',
      'logout': 'Logout',
      'loginSuccess': 'Login successfully',
      'login': 'Login',
      'loginSubtitle': 'Enter your email and password to continue',
      'usernameOrEmail': 'Username or Email',
      'password': 'Password',
      'forgotPasswordPrompt': 'Forgot password?',
      'orContinueWith': 'Or continue with',
      'noAccountPrompt': 'Don\'t have an account? ',
      'registerNow': 'Register now',
      'google': 'Google',
      'facebook': 'Facebook',
      'registerInfo': 'Fill the information below to register',
      'fullName': 'Full Name',
      'username': 'Username',
      'email': 'Email',
      'confirmPassword': 'Confirm Password',
      'register': 'Register',
      'alreadyHaveAccount': 'Already have an account? ',
      'forgotPasswordTitle': 'Forgot Password?',
      'forgotPasswordSubtitle': 'Enter the email associated with your account to receive a reset link.',
      'enterYourEmail': 'Enter your email',
      'sendLink': 'Send Link',
      'backToLogin': 'Back to Login',
      'facebookNotDeveloped': 'Facebook login is in development',
      
      'val_email_username_empty': 'Please enter username or email',
      'val_username_length': 'Username must be at least 6 characters',
      'val_email_invalid': 'Invalid email format',
      'val_email_empty': 'Please enter your email',
      'val_password_empty': 'Please enter your password',
      'val_password_length': 'Password must be at least 6 characters',
      'val_password_complexity': 'Password must contain uppercase, lowercase, numbers, and special chars',
      'val_username_empty': 'Please enter your username',
      'val_confirm_password_empty': 'Please confirm your password',
      'val_password_mismatch': 'Passwords do not match',
      'val_fullname_empty': 'Full name cannot be empty',
    },
    'vi': {
      'settingsTitle': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'theme': 'Giao diện',
      'lightTheme': 'Sáng',
      'darkTheme': 'Tối',
      'systemTheme': 'Hệ thống',
      'english': 'Tiếng Anh',
      'vietnamese': 'Tiếng Việt',
      'homeTitle': 'Trang chủ',
      'adminPanelTitle': 'Quản trị viên',
      'adminPanelSubtitle': 'Quản lý địa điểm, tài liệu học tập và báo cáo người dùng',
      'managePlaces': 'Quản lý địa điểm',
      'manageDocuments': 'Quản lý tài liệu',
      'reviewReports': 'Duyệt báo cáo',
      'featuredContent': 'Nội dung nổi bật',
      'approvalQueue': 'Hàng chờ duyệt',
      'moderationSectionTitle': 'Công cụ kiểm duyệt',
      'placesAdminDescription': 'Duyệt, ẩn và sắp xếp các địa điểm học tập do người dùng chia sẻ.',
      'documentsAdminDescription': 'Kiểm duyệt tài liệu học tập, nhãn và chất lượng trước khi xuất bản.',
      'quickActions': 'Thao tác nhanh',
      'quickActionAddPlace': 'Thêm địa điểm',
      'quickActionReviewPlace': 'Duyệt địa điểm',
      'quickActionAddDocument': 'Thêm tài liệu',
      'quickActionReviewDocument': 'Duyệt tài liệu',
      'reportReasonLabel': 'Lý do',
      'reportByLabel': 'Báo cáo bởi',
      'dismissReportButton': 'Bỏ qua',
      'takeActionButton': 'Xử lý',
      'approveButton': 'Duyệt',
      'rejectButton': 'Từ chối',
      'setFeaturedButton': 'Đặt nổi bật',
      'active': 'Đang hoạt động',
      'pending': 'Chờ duyệt',
      'totalItems': 'Tổng mục',
      'viewAll': 'Xem tất cả',
      'homeWelcomeSubtitle': 'Khám phá địa điểm và tài liệu học tập từ cộng đồng',
      'searchHint': 'Tìm địa điểm, tài liệu, chủ đề...',
      'newPlacesMetric': 'Địa điểm mới',
      'newDocumentsMetric': 'Tài liệu mới',
      'savedMetric': 'Đã lưu',
      'newAndFeaturedSection': 'Địa điểm và tài liệu mới, nổi bật',
      'filterButton': 'Lọc',
      'featuredPlaceTitle': 'Quan cafe học nhóm gần trường',
      'featuredPlaceSubtitle': 'Không gian yên tĩnh, wifi ổn định, mở cửa đến 23h',
      'featuredDocTitle': 'Bộ tài liệu IELTS Writing Task 2',
      'featuredDocSubtitle': 'Checklist cập nhật và bài mẫu band 7+',
      'placeTag': 'Địa điểm',
      'documentTag': 'Tài liệu',
      'mySharingSection': 'Không gian chia sẻ của tôi',
      'myPostsButton': 'Bài đăng của tôi',
      'newPostButton': 'Đăng bài mới',
      'shareDocumentButton': 'Chia sẻ tài liệu',
      'openMapButton': 'Mở bản đồ',
      'mapExploreTitle': 'Khám phá bản đồ',
      'searchPageTitle': 'Tìm kiếm',
      'suggestedKeywords': 'Từ khóa gợi ý',
      'filterPageTitle': 'Lọc nội dung',
      'featuredOnly': 'Chỉ nội dung nổi bật',
      'distanceRangeLabel': 'Khoảng cách',
      'applyFilterButton': 'Áp dụng bộ lọc',
      'discoverPageTitle': 'Khám phá địa điểm và tài liệu',
      'postTitleLabel': 'Tiêu đề bài đăng',
      'postContentLabel': 'Nội dung bài đăng',
      'publishPostButton': 'Đăng bài',
      'documentTitleLabel': 'Tên tài liệu',
      'documentSubjectLabel': 'Môn học / danh mục',
      'documentDescriptionLabel': 'Mô tả',
      'pickDocumentButton': 'Chọn tệp',
      'submitDocumentButton': 'Gửi tài liệu',
      'logout': 'Đăng xuất',
      'loginSuccess': 'Đăng nhập thành công',
      'login': 'Đăng nhập',
      'loginSubtitle': 'Nhập email và mật khẩu của bạn để tiếp tục',
      'usernameOrEmail': 'Tên đăng nhập hoặc Email',
      'password': 'Mật khẩu',
      'forgotPasswordPrompt': 'Quên mật khẩu?',
      'orContinueWith': 'Hoặc tiếp tục với',
      'noAccountPrompt': 'Chưa có tài khoản? ',
      'registerNow': 'Đăng ký ngay',
      'google': 'Google',
      'facebook': 'Facebook',
      'registerInfo': 'Điền thông tin dưới đây để đăng ký',
      'fullName': 'Họ và tên',
      'username': 'Tên đăng nhập',
      'email': 'Email',
      'confirmPassword': 'Nhập lại mật khẩu',
      'register': 'Đăng ký',
      'alreadyHaveAccount': 'Đã có tài khoản? ',
      'forgotPasswordTitle': 'Quên mật khẩu?',
      'forgotPasswordSubtitle': 'Hãy nhập email liên kết với tài khoản của bạn để nhận liên kết đặt lại mật khẩu.',
      'enterYourEmail': 'Nhập email của bạn',
      'sendLink': 'Gửi liên kết',
      'backToLogin': 'Quay lại trang đăng nhập',
      'facebookNotDeveloped': 'Đăng nhập Facebook đang được phát triển',
      
      'val_email_username_empty': 'Vui lòng nhập tên đăng nhập hoặc email',
      'val_username_length': 'Tên đăng nhập phải từ 6 ký tự',
      'val_email_invalid': 'Email không hợp lệ',
      'val_email_empty': 'Vui lòng nhập email',
      'val_password_empty': 'Vui lòng nhập mật khẩu',
      'val_password_length': 'Mật khẩu phải từ 6 ký tự',
      'val_password_complexity': 'Mật khẩu phải chứa chữ hoa, thường, số và ký tự đặc biệt',
      'val_username_empty': 'Vui lòng nhập tên đăng nhập',
      'val_confirm_password_empty': 'Vui lòng nhập lại mật khẩu',
      'val_password_mismatch': 'Mật khẩu xác nhận không khớp',
      'val_fullname_empty': 'Họ tên không được để trống',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class AppLangugeDelegate extends LocalizationsDelegate<AppLanguge> {
  const AppLangugeDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'vi'].contains(locale.languageCode);

  @override
  Future<AppLanguge> load(Locale locale) async => AppLanguge(locale);

  @override
  bool shouldReload(AppLangugeDelegate old) => false;
}
